name: Add PR to Project V2

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Add PR to Project V2
      run: |
        PROJECT_ID="3"
        url=${{ github.event.pull_request.html_url }}
        echo "$PROJECT_ID, $url"
        gh project item-add $PROJECT_ID --owner Lesords --url "$url"
      env:
        GITHUB_TOKEN: ${{ secrets.Lesords }}
        PR_ID: ${{ github.event.pull_request.node_id }}
