name: Add PR to Project V2

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Add PR to Project V2
      run: |
        PROJECT_ID="3"
        echo "$PR_ID, $PR_ID_2"
        gh api graphql -f query='
          mutation($project:ID!, $pr:ID!) {
            addProjectV2ItemById(input: {projectId: $project, contentId: $pr}) {
              item {
                id
              }
            }
          }' -f project=$PROJECT_ID -f pr=$PR_ID --jq '.data.addProjectV2ItemById.item.id'
      env:
        GITHUB_TOKEN: ${{ secrets.Lesords }}
        PR_ID: ${{ github.event.pull_request.node_id }}
