name: Add PR to Project V2

on:
  pull_request:
    types: [opened, reopened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Add PR to Project V2
      run: |
        gh project item-add $PROJECT_ID --owner Lesords --url "$URL"
      env:
        PROJECT_ID: "3"
        URL: ${{ github.event.pull_request.html_url }}
        GITHUB_TOKEN: ${{ secrets.Lesords }}
